from . import views
# imports all of the functions i have created in views
from django.contrib.auth import views as auth_views
# imports authorisation views
from django.urls import path
# imports path to link to urls that html files are connected to
# everything aove this line was autogenerated by django
urlpatterns = [
    path('', views.Index, name='index'),
    path('Login', auth_views.LoginView.as_view(template_name='Home/Student.html'), name='Login'),
    path('Logout', auth_views.LogoutView.as_view(template_name='Home/logout.html'), name='Logout'),
    path('SignUp', views.SignUp, name='SignUp'),
    path('Profile', views.Profile, name='Profile'),
    path('Profile/<int:pk>', views.Profile, name='ViewOtherProfile'),
    path('Profile/Edit', views.EditProfile, name='EditProfile'),
    path('Posts', views.Posts, name='Posts'),
    path('Posts/<int:pk>/', views.PostDetail, name='PostDetail'),
    path('Posts/results/', views.Search, name='Search'),
    path('Like', views.LikePost, name='LikePost'),
    path('Delete', views.DeletePost, name='DeletePost'),
    path('Create Post', views.CreatePost, name='CreatePost'),
    path('Friends', views.Friends, name='Friends'),
    path('AddFriends', views.AddFriend, name='AddFriend'),
    path('connect/<operation>/<int:pk>', views.ChangeFriendStatus, name='ChangeFriendStatus'),
    path('AddFriends/results/', views.SearchFriends, name='SearchFriends')
]
# this links each of the views in the views.py file to a url
# to be accessed when needed
