# Generated by Django 2.1.2 on 2019-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190208_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='DateAndTime',
        ),
    ]
